version: '3.4'

services:
  homeassistant:
    container_name: home-assistant
    restart: always
    image: homeassistant/home-assistant:latest

    volumes:
      - ${USERDIR}/ha/config:/config
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/home-assistant/media:/media
    privileged: true
    ports:
      - 8123:8123
    environment:
      - TZ=${TZ}  
 
networks:
  default:
    external:
      name: iot-smart-network  
