version: '3.4'
x-logging: &loki-logging
  driver: loki
  options: # note: the ip is the ip we will assign later to loki in this file
    loki-url: "http://localhost:3100/loki/api/v1/push"

services:
  homeassistant:
    container_name: ${ENV_NAME_PREFIX}-home-assistant
    restart: always
    image: homeassistant/home-assistant:2022.10.5

    volumes:
      - ${USERDIR}/ha/config:/config
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/home-assistant/media:/media
    privileged: true
    ports:
      - 8123:8123
    environment:
      - TZ=${TZ}
    logging: *loki-logging
  auth-proxy:
    # can base on https://github.com/grafana/grafana/issues/52681
    # https://developer.okta.com/blog/2022/07/14/add-auth-to-any-app-with-oauth2-proxy
    #config link https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    container_name: ${ENV_NAME_PREFIX}-auth-proxy
    restart: always
    depends_on:
      - proxy-server
    ports:
      - 4180:4180
    volumes:
      - ${USERDIR}/oauth2:/var/lib/oauth2_proxy
    environment:
      # DOC https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#azure-auth-provider
      - OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR=true
      - OAUTH2_PROXY_PROVIDER=azure
      - OAUTH2_PROXY_AZURE_TENANT=${TENANT}
      - OAUTH2_PROXY_CLIENT_ID=${AZURE_AD_HA_APP}
      - OAUTH2_PROXY_CLIENT_SECRET=${AZURE_AD_HA_SECRET}
      - OAUTH2_PROXY_OIDC_ISSUER_URL=${AZURE_AD_ISSUER}
      - OAUTH2_PROXY_OIDC_EMAIL_CLAIM=upn
      - OAUTH2_PROXY_UPSTREAMS=${HA_URL}

      - OAUTH2_PROXY_REVERSE_PROXY=true

      - OAUTH2_PROXY_COOKIE_SECRET=${COOKIE_SECRET}
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_COOKIE_SECURE=false
      
      - OAUTH2_PROXY_HTTP_ADDRESS=http://:4180
      - OAUTH2_PROXY_REDIRECT_URL=${REDIRECT_URL}
      #- OAUTH2_PROXY_COOKIE_DOMAINS=${COOKIE_DOMAIN}
      #- OAUTH2_PROXY_WHITELIST_DOMAINS=${COOKIE_DOMAIN}
      - OAUTH2_PROXY_SSL_UPSTREAM_INSECURE_SKIP_VERIFY=true
      - OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY=true
      - OAUTH2_PROXY_STANDARD_LOGGING=true
      - OAUTH2_PROXY_AUTH_LOGGING=true
      - OAUTH2_PROXY_REQUEST_LOGGING=true
      - OAUTH2_PROXY_ERRORS_TO_INFO_LOG=true
      - OAUTH2_PROXY_PASS_USER_HEADERS=true
      - OAUTH2_PROXY_set_xauthrequest=true
      - OAUTH2_PROXY_pass_access_token=true
    #logging: *loki-logging
  proxy-server:
    image: nginx:1.19
    container_name: ${ENV_NAME_PREFIX}-proxy-server
    ports:
      - 443:443
    restart: always
    volumes:
      - ./nginx-config/templates:/etc/nginx/templates
      - ./nginx-config/cert.pem.secret:/etc/nginx/ssl/cert.pem:ro
      - ./nginx-config/key.pem.secret:/etc/nginx/ssl/key.pem:ro
      - ./nginx-config/passw.secret:/etc/nginx/ssl/passw:ro
      - ./nginx-config/nginx.conf:/etc/nginx/conf.d/default.conf
    #logging: *loki-logging
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ${USERDIR}/certbot/www/:/var/www/certbot/:rw
  #     - ${USERDIR}/certbot/conf/:/etc/letsencrypt/:rw

networks:
  default:
    external:
      name: iot-smart-network
