version: '3.7'
x-logging: &loki-logging
  driver: loki
  options: # note: the ip is the ip we will assign later to loki in this file
    loki-url: "http://localhost:3100/loki/api/v1/push"

services:
  portainer:
    container_name: portainer
    restart: always  
    image: portainer/portainer:latest
    volumes:
      - ${USERDIR}/portainer:/data
      - ${USERDIR}/shared:/shared
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    environment:
      - TZ=${TZ}
    logging: *loki-logging  
networks:
  default:
    external:
      name: shared-smart-network