# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
my:

logger:
  default: info
  logs:
    homeassistant.components.influxdb: warning
    homeassistant.components.mqtt: info
    custom_components.auth_header: info
    
http:
    use_x_forwarded_for: true
    ip_ban_enabled: false
    login_attempts_threshold: 100
    trusted_proxies:
    - 172.23.0.0/24
auth_header:
    # Optionally set this if you're not using authentik proxy or oauth2_proxy
    username_header: X-Forwarded-Email
    # Optionally enable debug mode to see the headers Home-Assistant gets
    debug: true

# Example configuration.yaml entry
switch:
  - platform: template
    switches:
      skylight:
        value_template: "{{ is_state('sensor.skylight', 'on') }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.virtual_alarm_enabled
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.virtual_alarm_enabled

input_boolean:
  virtual_notify_home:
    name: Notify when someone arrives home

  virtual_alarm_enabled:
    name: Enable/disable virtual alarm

prometheus:
  namespace: hass