# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
my:

logger:
  default: info
  logs:
    homeassistant.components.influxdb: warning
    homeassistant.components.mqtt: debug
    custom_components.auth_header: debug
    
http:
    use_x_forwarded_for: true
    trusted_proxies:
        - 0.0.0.0/0 # This needs to be set to the IP of your reverse proxy
auth_header:
    # Optionally set this if you're not using authentik proxy or oauth2_proxy
    username_header: X-Forwarded-Email
    # Optionally enable debug mode to see the headers Home-Assistant gets
    # debug: false

# Example configuration.yaml entry
switch:
  - platform: template
    switches:
      skylight:
        value_template: "{{ is_state('sensor.skylight', 'on') }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.skylight_open
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.skylight_close   

