# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


logger:
  default: info
  logs:
    homeassistant.components.influxdb: warning
    homeassistant.components.mqtt: debug

# Example configuration.yaml entry
switch:
  - platform: template
    switches:
      skylight:
        value_template: "{{ is_state('sensor.skylight', 'on') }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.skylight_open
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.skylight_close