name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18.0.0']

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      #- name: Copy .env
      #  run: cp .env.dist .env
      - name: Build QUEUE docker-compose stack
        run: docker-compose up docker/queue/docker-compose.yaml --env-file docker/.env
      - name: Build MANAGEMENT docker-compose stack
        run: docker-compose up docker/management/docker-compose.yaml --env-file docker/.env
      - name: Build OBSERVABILITY docker-compose stack
        run: docker-compose up docker/observability/docker-compose.yaml --env-file docker/.env
      - name: Build HA docker-compose stack
        run: docker-compose up docker/home-assistant/docker-compose.yaml  --env-file docker/.env
      - name: Check running containers
        run: docker ps -a