name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18.0.0']

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      #- name: 🚀 Run yamllint
      #  uses: frenck/action-yamllint@v1
      #- name: Copy .env
      #  run: cp .env.dist .env
      - name: Build SHARED docker-compose stack
        run: docker network create iot-smart-network
      - name: Build QUEUE docker-compose stack
        working-directory: ./docker/queue
        run: docker-compose up --env-file ../docker/.env
      - name: Build MANAGEMENT docker-compose stack
        working-directory: ./docker/management/
        run: docker-compose up --env-file ../docker/.env
      - name: Build OBSERVABILITY docker-compose stack
        working-directory: ./docker/observability/
        run: docker-compose up --env-file ../docker/.env
      - name: prepare to run HA
        working-directory: .
        run: ha-run.sh
      - name: Build HA docker-compose stack
        working-directory: ./docker/home-assistant/
        run: docker-compose up  --env-file docker/.env
      - name: Check running containers
        run: docker ps -a