name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18.0.0']

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      #- name: 🚀 Run yamllint
      #  uses: frenck/action-yamllint@v1
      #- name: Copy .env
      #  run: cp .env.dist .env

      - name: Build QUEUE docker-compose stack
        working-directory: docker
        run: run.sh
        shell: bash