---
name: Home Assistant CI

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  yamllint:
    name: 🧹 yamllint 
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Running YAMLlint
        uses: ibiqlik/action-yamllint@v1
        continue-on-error: true
        with:
          config_file: .github/yamllint-config.yml

  remarklint:
    runs-on: ubuntu-18.04
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v3.0.2
      - name: Running Remark lint
        uses: "docker://pipelinecomponents/remark-lint:latest"
        continue-on-error: true
        with:
          args: "remark --no-stdout --color --frail --use preset-lint-recommended ."

  home-assistant:
    name: "Home Assistant Core ${{ matrix.version }} Configuration Check"
    needs: [yamllint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["stable"]
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v3.0.2
      - name: 🚀 Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@v1.3
        with:
          path: "./home-assistant-configuration"
          secrets: ./home-assistant-configuration/secrets_github.yaml
          version: "${{ matrix.version }}"

  # esphome:
  #   runs-on: ubuntu-latest
  #   needs: [yamllint]
  #   steps:
  #     - name: ⤵️ Check out configuration from GitHub
  #       uses: actions/checkout@v3.0.2
  #     - name: Set up Python 3.7
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: 3.7
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip setuptools wheel
  #         pip install esphome
  #         pip list
  #         esphome version
  #     - name: Copy secrets stub into configuration folder
  #       run: cp ./secrets_github.yaml ./esphome/secrets.yaml
  #     - name: Run esphome on all files
  #       # yamllint disable rule:line-length
  #       run: |
  #         for file in $(find ./config/esphome -type f -name "*.yaml" -maxdepth 1 -not -name "secrets.yaml"); do esphome "${file}" config; done

